
package org.tinygroup.jdbctemplatedslsession.daosupport;

import java.io.Serializable;
import java.util.List;

import org.tinygroup.tinysqldsl.Pager;

/**
 * 基础dao类
 * @author renhui
 *
 * @param <T>
 */
public interface BaseDao <T>{

	public T insertObject(T t);

	public T insertObject(boolean autoGeneratedKeys ,T t);

	public int updateObject(T t);

	public int deleteObject(Serializable pk);

	public T getObjectById(Serializable pk);

	public int deleteObjects(Serializable... pks);

	public List<T> queryObjects(T t);

	public Pager<T> queryObjectsForPage (int start ,int limit ,T t);

	public int[] batchInsert(List<T> objs);

	public int[] batchInsert(boolean autoGeneratedKeys ,List<T> objs);

	public int[] batchUpdate(List<T> objs);

	public int[] batchDelete(List<T> objs);

}
